version: '3.3'


services:
  app:
    build:
      dockerfile: ./app/Dockerfile
    #image: cyruschan7/dockerized-app:latest
    #depends_on:
    #  - db2
    env_file: variables.env

  web:
    build:
      dockerfile: ./html/Dockerfile
    #image: cyruschan7/dockerized-web:latest
    ports:
      - 12345:80
    env_file: variables.env