version: '3.3'


services:
  app:
    build:
      dockerfile: ./app/Dockerfile
    #image: cyruschan7/eval4640-app:latest
    env_file: variables.env

  web:
    build:
      dockerfile: ./html/Dockerfile
    #image: cyruschan7/eval4640-web:latest
    ports:
      - 12345:80
    env_file: variables.env